/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  CallContractParams,
  CallContractResult,
  Contract,
  ContractEvent,
  ContractFactory,
  ContractInstance,
  ContractState,
  EventSubscribeOptions,
  EventSubscription,
  HexString,
  TestContractParams,
  TestContractResult,
  callMethod,
  fetchContractState,
  getContractEventsCurrentCount,
  multicallMethods,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
} from "@alephium/web3";

import { default as PresaleTokenContractJson } from "../PresaleToken.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace PresaleTokenTypes {
  export type Fields = {
    symbol: HexString;
    name: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  PresaleTokenInstance,
  PresaleTokenTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as PresaleTokenTypes.Fields;
  }

  consts = { Ap: BigInt(2) };

  at(address: string): PresaleTokenInstance {
    return new PresaleTokenInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParams<PresaleTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getSymbol", params);
    },
    getName: async (
      params: Omit<
        TestContractParams<PresaleTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getName", params);
    },
    getDecimals: async (
      params: Omit<
        TestContractParams<PresaleTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParams<PresaleTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getTotalSupply", params);
    },
  };
}

// Use this object to test and deploy the contract
export const PresaleToken = new Factory(
  Contract.fromJson(
    PresaleTokenContractJson,
    "",
    "68b5b8ea856a1bbaf28fb8f2495d8a2b2d13c8c0ef436eebe2880f837ba98d1b"
  )
);

// Use this class to interact with the blockchain
export class PresaleTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<PresaleTokenTypes.State> {
    return fetchContractState(PresaleToken, this);
  }

  methods = {
    getSymbol: async (
      params?: PresaleTokenTypes.CallMethodParams<"getSymbol">
    ): Promise<PresaleTokenTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        PresaleToken,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: PresaleTokenTypes.CallMethodParams<"getName">
    ): Promise<PresaleTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        PresaleToken,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: PresaleTokenTypes.CallMethodParams<"getDecimals">
    ): Promise<PresaleTokenTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        PresaleToken,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: PresaleTokenTypes.CallMethodParams<"getTotalSupply">
    ): Promise<PresaleTokenTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        PresaleToken,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends PresaleTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<PresaleTokenTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      PresaleToken,
      this,
      calls,
      getContractByCodeHash
    )) as PresaleTokenTypes.MultiCallResults<Calls>;
  }
}
