/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as TransferScriptJson } from "../transfer.ral.json";

export namespace Transfer {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      shinyTokenId: HexString;
      to: HexString;
      amount: bigint;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(TransferScriptJson);
}
