/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as DestroyScriptJson } from "../Destroy.ral.json";
import { default as TransferScriptJson } from "../Transfer.ral.json";

export const Destroy = new ExecutableScript<{
  shinyToken: HexString;
  to: Address;
}>(Script.fromJson(DestroyScriptJson, "", []), getContractByCodeHash);

export const Transfer = new ExecutableScript<{
  shinyToken: HexString;
  to: Address;
  amount: bigint;
}>(Script.fromJson(TransferScriptJson, "", []), getContractByCodeHash);
