import { BarBackButton, BarCloseButton, NavigationContainer } from "@argent/ui"
import { FC } from "react"
import { Navigate, useNavigate } from "react-router-dom"

import { Option, OptionsWrapper } from "../../components/Options"
import { PageWrapper } from "../../components/Page"
import { A } from "../../components/TrackingLink"
import { routes } from "../../routes"
import { trackAddFundsService } from "../../services/analytics"
import { useSelectedAccount } from "../accounts/accounts.state"
import EthereumSvg from "./ethereum.svg"
import { Title } from "./FundingScreen"
import OrbiterSvg from "./orbiter.svg"
