name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - run: yarn install --frozen-lockfile
      - run: |
          echo 'module.exports.basePath = "/extension-wallet"' >> packages/dapp/next.config.js
      - run: yarn build
        env:
          UPLOAD_SENTRY_SOURCEMAPS: false

      - run: yarn --cwd packages/dapp export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/dapp/out
