name: Run Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 1000000

      # - name: Lint
      #   run: yarn lint

      - name: Build
        run: yarn build
        env:
          UPLOAD_SENTRY_SOURCEMAPS: false

      # - name: Run tests
      #   run: yarn test

      # - name: Run e2e tests
      #   run: xvfb-run --auto-servernum yarn test:e2e

      # - uses: actions/upload-artifact@v3
      #   if: failure()
      #   with:
      #     name: test-results
      #     path: packages/extension/test-results/

      # - name: Check bundlesize
      #   run: yarn run bundlewatch
